version: '3.8'

services:
  frontend:
    build: ./frontend
    ports: 
      - 3000:3000
  backend:
    container_name: metatollbackendcontainer
    restart: always
    build: ./backend
    ports:
      - 9103:9103
    depends_on:
      - mongo_db
      - redis
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo_db:27017/metatolldb
      NAME: SG

  mongo_db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_dbdata:/data/db

  redis:
    container_name: redis-container
    image: redis
    restart: always
    ports:
      - 6379:6379

volumes:
  mongo_dbdata: