version: '3.8'

services:
  backend:
    container_name: metatollbackendcontainer
    restart: always
    build: ./backend
    ports:
      - 9103:9103
    depends_on:
      - mongo_db
    environment:
      # PORT: 3000
      # ME_CONFIG_MONGODB_ADMINUSERNAME: appAdmin
      # ME_CONFIG_MONGODB_ADMINPASSWORD: appAdmin123
      # ME_CONFIG_MONGODB_URL: mongodb://appAdmin:appAdmin123@mongo_db:27017/metatolldb
      ME_CONFIG_MONGODB_URL: mongodb://mongo_db:27017/metatolldb
      NAME: TOPG

  mongo_db:
    # container_name: mymongo
    image: mongo:latest
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: appAdmin
    #   MONGO_INITDB_ROOT_PASSWORD: appAdmin123
    #   MONGO_INITDB_ROOT_DATABASE: metatolldb
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - mongo_dbdata:/data/db

volumes:
  mongo_dbdata: